import { createContext, useContext, useState, type ReactNode } from "react";

export type RuntimeMode = "mock" | "backend";
export type AppLanguage = "en" | "zh" | "de";

export const LANGUAGES: { value: AppLanguage; label: string; flag: string }[] = [
  { value: "en", label: "English", flag: "🇬🇧" },
  { value: "zh", label: "中文", flag: "🇨🇳" },
  { value: "de", label: "Deutsch", flag: "🇩🇪" },
];

// All UI strings
export const i18n: Record<AppLanguage, Record<string, string>> = {
  en: {
    nav_brand: "MAPA",
    hero_badge: "Consent-First · Privacy-Safe · No Diagnosis",
    hero_title_1: "Multimodal Accessibility",
    hero_title_2: "Profiling Agent",
    hero_subtitle: "Multilingual prototype for consent-first accessibility profiling and personalized journey planning.",
    hero_cta: "Start Profiling",
    hero_narration: "Hi. You are using MAPA, the Multimodal Accessibility Profiling Agent. {runtime} The default speech language is English. MAPA supports English, Chinese, and German. After allowing the microphone on the permissions page, say English, Chinese, or German to switch language. Select Start Profiling to continue.",
    hero_runtime_mock: "The current runtime is deterministic Mock mode.",
    hero_runtime_backend_ollama: "The current runtime is Backend. Text model: {text}. Speech model: {speech}. Vision model: {vision}.",
    page_speech_read: "Read this page",
    page_speech_stop: "Stop reading",
    agent_consent_guard: "Consent Guard",
    agent_profiler: "Profiler Agent",
    agent_profile_mgr: "Profile Manager",
    agent_hazard: "Hazard Fusion",
    consent_title: "Permissions",
    consent_desc: "Choose what to enable. Both are optional. No data is stored or sent anywhere.",
    consent_narration: "Permissions. Before profiling, choose whether to allow the camera and microphone. First, Camera. The camera opens a local preview for optional route hazard input. Second, Microphone. The microphone enables voice input for profiling. After allowing it, say English, Chinese, or German to switch language. Both permissions are optional. Select Continue when ready.",
    consent_camera: "Camera",
    consent_camera_desc: "Open a local preview for optional route-hazard input.",
    consent_mic: "Microphone",
    consent_mic_desc: "Voice input for profiling",
    consent_enable_camera: "Allow camera",
    consent_enable_mic: "Allow microphone",
    consent_enabled: "Enabled",
    consent_continue: "Continue",
    consent_back: "← Back to home",
    consent_cam_denied: "Camera access denied.",
    consent_mic_denied: "Microphone access denied.",
    consent_still_continue: "You can still continue.",
    chat_title: "Accessibility Profiling",
    chat_step: "Step {current} of {total}",
    chat_turn: "Turns so far: {current}",
    chat_show_traces: "Show Agent Traces",
    chat_hide_traces: "Hide Agent Traces",
    chat_skip: "Skip",
    chat_input_voice: "Voice",
    chat_input_text: "Text",
    chat_speech_on: "Speech On",
    chat_speech_stop: "Stop speaking",
    chat_speech_replay: "Speak this message",
    chat_speech_off: "Speech Off",
    chat_placeholder: "Type or speak your answer...",
    chat_back: "← Back",
    chat_no_data: "You can skip any question. No data is stored.",
    chat_thinking: "Thinking...",
    chat_recording: "Recording...",
    chat_transcribing: "Transcribing speech...",
    chat_transcription_failed:
      "I couldn't transcribe that recording. Please try again or type your answer.",
    chat_voice_unsupported: "Your browser does not support microphone recording.",
    chat_complete: "Thank you! Here is what I understood. I'll now build your personalized profile and route plan.",
    chat_confirm_prompt: "Is this correct? You can say yes, no, or tell me what to change.",
    chat_confirm_route_step_free: "Based on this, I will use a step-free route.",
    chat_confirm_route_standard: "Based on this, I will use a standard route.",
    chat_revise_prompt: "Tell me what I should change. You can mention several items at once.",
    chat_confirmed: "Confirmed. I will create your route plan now.",
    chat_switched_en: "Switched to English.",
    chat_switched_zh: "已切换为中文。",
    chat_switched_de: "Auf Deutsch gewechselt.",
    result_title: "Your Accessibility Profile",
    result_confidence: "Confidence: {value}%",
    result_no_needs: "No specific needs detected",
    result_tab_plan: "Route Plan",
    result_tab_profile: "Profile",
    result_tab_json: "JSON",
    result_route_plan: "Route Plan",
    result_alerts: "Alerts",
    result_checklist: "Checklist",
    result_open_data: "Open Data Snapshot",
    result_sources: "Sources",
    result_affects: "Affects",
    result_freshness_current: "current",
    result_freshness_reference: "reference",
    result_hotspots: "Barrier Hotspots",
    result_nearby: "Nearby Amenities",
    result_live_context: "Data-aware route context",
    result_source_live: "Live Zurich OGD",
    result_source_mock: "Mock Zurich OGD preview",
    result_updated: "Updated {value}",
    result_read_all: "Read route plan, alerts, and checklist",
    result_stop_reading: "Stop reading",
    result_trace_title: "Planning Agent Trace",
    result_refine: "Review or update",
    result_restart: "Start Over",
    camera_off: "Camera is off",
    camera_live: "Live",
    settings_title: "Runtime Settings",
    settings_mode: "Mode",
    settings_ollama_url: "Ollama URL",
    settings_ollama_hint: "Run ollama serve locally",
    settings_ollama_model: "Ollama Model",
    settings_text_model: "Text model",
    settings_speech_model: "Speech model",
    settings_vision_model: "Vision model",
    settings_ollama_model_hint: "Recommended: shmily_006/Qw3:4b_4bit (4-bit, ~2.5 GB, fast). Alt: qwen3.5:4b, llama3.1:8b.",
    settings_offline: "Deterministic Mock mode",
    settings_ollama_req: "Requires local Ollama instance",
    mock_label: "Mock",
    mock_desc: "Offline deterministic",
    ollama_label: "Ollama",
    ollama_desc: "Local LLM",
    backend_label: "Backend",
    backend_desc: "Python FastAPI",
    settings_backend_url: "Backend URL",
    settings_backend_hint: "Run: uvicorn backend.app.api:app",
    settings_backend_req: "Requires local Python backend",
  },
  zh: {
    nav_brand: "MAPA",
    hero_badge: "隐私优先 · 知情同意 · 无诊断",
    hero_title_1: "多模态无障碍",
    hero_title_2: "分析代理",
    hero_subtitle: "面向知情同意优先的无障碍出行分析与个性化路线规划的多语言原型。",
    hero_cta: "开始分析",
    hero_narration: "你好，你正在使用 MAPA 多模态无障碍分析代理。{runtime} 默认语音为英语。MAPA 支持英语、中文和德语。在权限页面允许麦克风后，可以说出英语、中文或德语来切换语言。请选择开始分析以继续。",
    hero_runtime_mock: "当前运行模式为确定性模拟模式。",
    hero_runtime_backend_ollama: "当前运行模式为后端模式。文本模型：{text}。语音模型：{speech}。视觉模型：{vision}。",
    page_speech_read: "朗读本页",
    page_speech_stop: "停止朗读",
    agent_consent_guard: "同意守护",
    agent_profiler: "分析代理",
    agent_profile_mgr: "档案管理",
    agent_hazard: "危险融合",
    consent_title: "权限设置",
    consent_desc: "选择要开启的功能。两项均为可选，数据不会被存储或发送。",
    consent_narration: "权限设置。在开始分析前，请选择是否允许摄像头和麦克风。第一，摄像头。摄像头会打开本地预览，用于可选的路线障碍输入。第二，麦克风。麦克风用于分析过程中的语音输入。允许后，可以说英语、中文或德语来切换语言。两项权限均为可选。准备好后请选择继续。",
    consent_camera: "摄像头",
    consent_camera_desc: "打开本地预览，用于可选的路线障碍输入。",
    consent_mic: "麦克风",
    consent_mic_desc: "语音输入",
    consent_enable_camera: "允许摄像头",
    consent_enable_mic: "允许麦克风",
    consent_enabled: "已开启",
    consent_continue: "继续",
    consent_back: "← 返回首页",
    consent_cam_denied: "摄像头权限被拒绝。",
    consent_mic_denied: "麦克风权限被拒绝。",
    consent_still_continue: "仍可继续使用。",
    chat_title: "无障碍分析",
    chat_step: "第 {current} 步，共 {total} 步",
    chat_turn: "已进行 {current} 轮",
    chat_show_traces: "显示代理链路",
    chat_hide_traces: "隐藏代理链路",
    chat_skip: "跳过",
    chat_input_voice: "语音",
    chat_input_text: "文字",
    chat_speech_on: "语音播报开",
    chat_speech_stop: "停止朗读",
    chat_speech_replay: "朗读此消息",
    chat_speech_off: "语音播报关",
    chat_placeholder: "输入或语音回答...",
    chat_back: "← 返回",
    chat_no_data: "您可以跳过任何问题，数据不会被存储。",
    chat_thinking: "思考中...",
    chat_recording: "录音中...",
    chat_transcribing: "正在转写语音...",
    chat_transcription_failed: "语音转写失败，请重试或直接输入文字。",
    chat_voice_unsupported: "当前浏览器不支持麦克风录音。",
    chat_complete: "谢谢！以下是我了解到的信息，接下来将为您生成个性化路线规划。",
    chat_confirm_prompt: "这些信息对吗？你可以回答“是”“否”，或直接告诉我哪里需要修改。",
    chat_confirm_route_step_free: "根据这些信息，我会优先使用无台阶路线。",
    chat_confirm_route_standard: "根据这些信息，我会使用标准路线。",
    chat_revise_prompt: "请告诉我需要修改什么。你可以一次说多个。",
    chat_confirmed: "已确认。我现在开始为你生成路线规划。",
    chat_switched_en: "Switched to English.",
    chat_switched_zh: "已切换为中文。",
    chat_switched_de: "Auf Deutsch gewechselt.",
    result_title: "您的无障碍档案",
    result_confidence: "置信度：{value}%",
    result_no_needs: "未检测到特定需求",
    result_tab_plan: "路线规划",
    result_tab_profile: "档案",
    result_tab_json: "JSON",
    result_route_plan: "路线规划",
    result_alerts: "提醒",
    result_checklist: "检查清单",
    result_open_data: "开放数据快照",
    result_sources: "数据来源",
    result_affects: "影响内容",
    result_freshness_current: "较新",
    result_freshness_reference: "参考数据",
    result_hotspots: "障碍热点",
    result_nearby: "附近设施",
    result_live_context: "带数据依据的路线环境",
    result_source_live: "苏黎世开放数据",
    result_source_mock: "苏黎世开放数据模拟预览",
    result_updated: "更新时间：{value}",
    result_read_all: "朗读路线、提醒和清单",
    result_stop_reading: "停止朗读",
    result_trace_title: "规划代理链路",
    result_refine: "检查或修改",
    result_restart: "重新开始",
    camera_off: "摄像头已关闭",
    camera_live: "实时",
    settings_title: "运行时设置",
    settings_mode: "模式",
    settings_ollama_url: "Ollama 地址",
    settings_ollama_hint: "本地运行 ollama serve",
    settings_ollama_model: "Ollama 模型",
    settings_text_model: "文本模型",
    settings_speech_model: "语音模型",
    settings_vision_model: "视觉模型",
    settings_ollama_model_hint: "推荐 shmily_006/Qw3:4b_4bit（4-bit，约 2.5 GB，较快）。备选 qwen3.5:4b、llama3.1:8b。",
    settings_offline: "确定性模拟模式",
    settings_ollama_req: "需要本地 Ollama 实例",
    mock_label: "模拟",
    mock_desc: "离线确定性",
    ollama_label: "Ollama",
    ollama_desc: "本地大模型",
    backend_label: "后端",
    backend_desc: "Python FastAPI",
    settings_backend_url: "后端地址",
    settings_backend_hint: "运行: uvicorn backend.app.api:app",
    settings_backend_req: "需要本地 Python 后端",
  },
  de: {
    nav_brand: "MAPA",
    hero_badge: "Einwilligung zuerst · Datenschutz · Keine Diagnose",
    hero_title_1: "Multimodale Barrierefreiheit",
    hero_title_2: "Profiling-Agent",
    hero_subtitle: "Mehrsprachiger Prototyp für einwilligungsbasiertes Barrierefreiheitsprofiling und personalisierte Routenplanung.",
    hero_cta: "Profiling starten",
    hero_narration: "Hallo. Sie verwenden MAPA, den multimodalen Barrierefreiheits-Profiling-Agenten. {runtime} Die Standardsprache der Sprachausgabe ist Englisch. MAPA unterstützt Englisch, Chinesisch und Deutsch. Nach Freigabe des Mikrofons auf der Berechtigungsseite können Sie Englisch, Chinesisch oder Deutsch sagen, um die Sprache zu wechseln. Wählen Sie Profiling starten, um fortzufahren.",
    hero_runtime_mock: "Der aktuelle Laufzeitmodus ist der deterministische Mock-Modus.",
    hero_runtime_backend_ollama: "Der aktuelle Laufzeitmodus ist Backend. Textmodell: {text}. Sprachmodell: {speech}. Bildmodell: {vision}.",
    page_speech_read: "Seite vorlesen",
    page_speech_stop: "Vorlesen stoppen",
    agent_consent_guard: "Einwilligungsschutz",
    agent_profiler: "Profiler-Agent",
    agent_profile_mgr: "Profilmanager",
    agent_hazard: "Gefahrenfusion",
    consent_title: "Berechtigungen",
    consent_desc: "Wählen Sie, was aktiviert werden soll. Beides ist optional. Es werden keine Daten gespeichert.",
    consent_narration: "Berechtigungen. Wählen Sie vor dem Profiling, ob Kamera und Mikrofon erlaubt werden. Erstens, Kamera. Die Kamera öffnet eine lokale Vorschau für optionale Routenhindernisse. Zweitens, Mikrofon. Das Mikrofon ermöglicht Spracheingaben während des Profilings. Danach können Sie Englisch, Chinesisch oder Deutsch sagen, um die Sprache zu wechseln. Beide Berechtigungen sind optional. Wählen Sie Weiter, wenn Sie bereit sind.",
    consent_camera: "Kamera",
    consent_camera_desc: "Lokale Vorschau für optionale Routenhindernisse öffnen",
    consent_mic: "Mikrofon",
    consent_mic_desc: "Spracheingabe",
    consent_enable_camera: "Kamera erlauben",
    consent_enable_mic: "Mikrofon erlauben",
    consent_enabled: "Aktiviert",
    consent_continue: "Weiter",
    consent_back: "← Zurück zur Startseite",
    consent_cam_denied: "Kamerazugriff verweigert.",
    consent_mic_denied: "Mikrofonzugriff verweigert.",
    consent_still_continue: "Sie können trotzdem fortfahren.",
    chat_title: "Barrierefreiheitsprofiling",
    chat_step: "Schritt {current} von {total}",
    chat_turn: "Bisher {current} Runden",
    chat_show_traces: "Agent-Trace anzeigen",
    chat_hide_traces: "Agent-Trace ausblenden",
    chat_skip: "Überspringen",
    chat_input_voice: "Sprache",
    chat_input_text: "Text",
    chat_speech_on: "Sprachausgabe an",
    chat_speech_stop: "Sprechen stoppen",
    chat_speech_replay: "Diese Nachricht vorlesen",
    chat_speech_off: "Sprachausgabe aus",
    chat_placeholder: "Antwort eingeben oder sprechen...",
    chat_back: "← Zurück",
    chat_no_data: "Sie können jede Frage überspringen. Keine Daten werden gespeichert.",
    chat_thinking: "Denke nach...",
    chat_recording: "Aufnahme läuft...",
    chat_transcribing: "Sprache wird transkribiert...",
    chat_transcription_failed:
      "Die Aufnahme konnte nicht transkribiert werden. Bitte erneut versuchen oder Text eingeben.",
    chat_voice_unsupported: "Dieser Browser unterstützt keine Mikrofonaufnahme.",
    chat_complete: "Vielen Dank! Hier ist, was ich verstanden habe. Ich erstelle jetzt Ihren personalisierten Routenplan.",
    chat_confirm_prompt: "Ist das richtig? Sie können ja, nein oder direkt die Korrektur eingeben.",
    chat_confirm_route_step_free: "Auf dieser Basis werde ich eine stufenfreie Route verwenden.",
    chat_confirm_route_standard: "Auf dieser Basis werde ich eine Standardroute verwenden.",
    chat_revise_prompt: "Bitte sagen Sie mir, was ich ändern soll. Sie können mehrere Punkte auf einmal nennen.",
    chat_confirmed: "Bestätigt. Ich erstelle jetzt Ihren Routenplan.",
    chat_switched_en: "Switched to English.",
    chat_switched_zh: "已切换为中文。",
    chat_switched_de: "Auf Deutsch gewechselt.",
    result_title: "Ihr Barrierefreiheitsprofil",
    result_confidence: "Konfidenz: {value}%",
    result_no_needs: "Keine speziellen Bedürfnisse erkannt",
    result_tab_plan: "Routenplan",
    result_tab_profile: "Profil",
    result_tab_json: "JSON",
    result_route_plan: "Routenplan",
    result_alerts: "Hinweise",
    result_checklist: "Checkliste",
    result_open_data: "Open-Data-Snapshot",
    result_sources: "Quellen",
    result_affects: "Wirkt auf",
    result_freshness_current: "aktuell",
    result_freshness_reference: "Referenzdaten",
    result_hotspots: "Barriere-Hotspots",
    result_nearby: "Nahe Einrichtungen",
    result_live_context: "Datenbasierter Routenkontext",
    result_source_live: "Live Zurich OGD",
    result_source_mock: "Mock-Vorschau von Zurich OGD",
    result_updated: "Aktualisiert: {value}",
    result_read_all: "Route, Hinweise und Checkliste vorlesen",
    result_stop_reading: "Vorlesen stoppen",
    result_trace_title: "Planungs-Agent-Trace",
    result_refine: "Prüfen oder ändern",
    result_restart: "Neu starten",
    camera_off: "Kamera ist aus",
    camera_live: "Live",
    settings_title: "Laufzeiteinstellungen",
    settings_mode: "Modus",
    settings_ollama_url: "Ollama-URL",
    settings_ollama_hint: "Lokal ollama serve ausführen",
    settings_ollama_model: "Ollama-Modell",
    settings_text_model: "Textmodell",
    settings_speech_model: "Sprachmodell",
    settings_vision_model: "Bildmodell",
    settings_ollama_model_hint: "Empfohlen: shmily_006/Qw3:4b_4bit (4-bit, ~2.5 GB, schnell). Alt: qwen3.5:4b, llama3.1:8b.",
    settings_offline: "Deterministischer Mock-Modus",
    settings_ollama_req: "Erfordert lokale Ollama-Instanz",
    mock_label: "Mock",
    mock_desc: "Offline deterministisch",
    ollama_label: "Ollama",
    ollama_desc: "Lokales LLM",
    backend_label: "Backend",
    backend_desc: "Python FastAPI",
    settings_backend_url: "Backend-URL",
    settings_backend_hint: "Starten: uvicorn backend.app.api:app",
    settings_backend_req: "Erfordert lokales Python-Backend",
  },
};

export function t(lang: AppLanguage, key: string, params?: Record<string, string | number>): string {
  let text = i18n[lang]?.[key] || i18n.en[key] || key;
  if (params) {
    Object.entries(params).forEach(([k, v]) => {
      text = text.replace(`{${k}}`, String(v));
    });
  }
  return text;
}

interface RuntimeContextType {
  mode: RuntimeMode;
  setMode: (mode: RuntimeMode) => void;
  ollamaUrl: string;
  setOllamaUrl: (url: string) => void;
  ollamaModel: string;
  setOllamaModel: (model: string) => void;
  speechModel: string;
  setSpeechModel: (model: string) => void;
  visionModel: string;
  setVisionModel: (model: string) => void;
  backendUrl: string;
  setBackendUrl: (url: string) => void;
  language: AppLanguage;
  setLanguage: (lang: AppLanguage) => void;
  speechOutputEnabled: boolean;
  setSpeechOutputEnabled: (enabled: boolean) => void;
}

const RuntimeContext = createContext<RuntimeContextType>({
  mode: "mock",
  setMode: () => {},
  ollamaUrl: "http://localhost:11434",
  setOllamaUrl: () => {},
  ollamaModel: "shmily_006/Qw3:4b_4bit",
  setOllamaModel: () => {},
  speechModel: "small",
  setSpeechModel: () => {},
  visionModel: "llava:7b",
  setVisionModel: () => {},
  backendUrl: "http://localhost:8000",
  setBackendUrl: () => {},
  language: "en",
  setLanguage: () => {},
  speechOutputEnabled: true,
  setSpeechOutputEnabled: () => {},
});

export const useRuntime = () => useContext(RuntimeContext);

export const RuntimeProvider = ({ children }: { children: ReactNode }) => {
  const [mode, setMode] = useState<RuntimeMode>("mock");
  const [ollamaUrl, setOllamaUrl] = useState("http://localhost:11434");
  const [ollamaModel, setOllamaModel] = useState("shmily_006/Qw3:4b_4bit");
  const [speechModel, setSpeechModel] = useState("small");
  const [visionModel, setVisionModel] = useState("llava:7b");
  const [backendUrl, setBackendUrl] = useState("http://localhost:8000");
  const [language, setLanguage] = useState<AppLanguage>("en");
  const [speechOutputEnabled, setSpeechOutputEnabled] = useState(true);

  return (
    <RuntimeContext.Provider
      value={{
        mode,
        setMode,
        ollamaUrl,
        setOllamaUrl,
        ollamaModel,
        setOllamaModel,
        speechModel,
        setSpeechModel,
        visionModel,
        setVisionModel,
        backendUrl,
        setBackendUrl,
        language,
        setLanguage,
        speechOutputEnabled,
        setSpeechOutputEnabled,
      }}
    >
      {children}
    </RuntimeContext.Provider>
  );
};
